<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use App\Models\Setting;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {

        $data = (array(

            0 =>
            array(
                'id' => 1,
                'name' => 'app_name',
                'val' => 'Kivilab: Your Ultimate Entertainment Hub',
                'type' => 'bussiness',
                'datatype' => 'bussiness',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:12:31',
                'updated_at' => '2024-08-08 10:12:31',
                'deleted_at' => NULL,
            ),
            1 =>
            array(
                'id' => 2,
                'name' => 'user_app_name',
<<<<<<< HEAD
                'val' => 'Kivilab: Your Ultimate Entertainment Hub',
=======
                'val' => 'carilab: Your Ultimate Entertainment Hub',
>>>>>>> aa9f34b78e4663033d47c5b897d43e1fb5088984
                'type' => 'bussiness',
                'datatype' => 'bussiness',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:12:31',
                'updated_at' => '2024-08-08 10:12:31',
                'deleted_at' => NULL,
            ),
            2 =>
            array(
                'id' => 3,
                'name' => 'helpline_number',
                'val' => '+15265897485',
                'type' => 'bussiness',
                'datatype' => 'bussiness',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:12:31',
                'updated_at' => '2024-08-08 10:12:31',
                'deleted_at' => NULL,
            ),
            3 =>
            array(
                'id' => 4,
                'name' => 'inquriy_email',
                'val' => 'hello@iqonic.design',
                'type' => 'bussiness',
                'datatype' => 'bussiness',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:12:31',
                'updated_at' => '2024-08-08 10:12:31',
                'deleted_at' => NULL,
            ),
            4 =>
            array(
                'id' => 5,
                'name' => 'short_description',
                'val' => 'Discover a world of endless entertainment with carilab. Your one-stop destination for movies, TV shows, and more, available anytime, anywhere.',
                'type' => 'bussiness',
                'datatype' => 'bussiness',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:12:31',
                'updated_at' => '2024-08-08 10:12:31',
                'deleted_at' => NULL,
            ),
            5 =>
            array(
                'id' => 6,
                'name' => 'google_analytics',
                'val' => 'Google Analytics',
                'type' => 'text',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
            6 =>
            array(
                'id' => 7,
                'name' => 'default_language',
                'val' => 'en',
                'type' => 'misc',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
            7 =>
            array(
                'id' => 8,
                'name' => 'default_time_zone',
                'val' => 'Asia/Kolkata',
                'type' => 'misc',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
            8 =>
            array(
                'id' => 9,
                'name' => 'disc_type',
                'val' => 'local',
                'type' => 'misc',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
            9 =>
            array(
                'id' => 10,
                'name' => 'cash_payment_method',
                'val' => '1',
                'type' => 'cashpayment',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            10 =>
            array(
                'id' => 11,
                'name' => 'razor_payment_method',
                'val' => '1',
                'type' => 'razorpayPayment',
                'datatype' => 'payment_gateways',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            11 =>
            array(
                'id' => 12,
                'name' => 'razorpay_secretkey',
                'val' => 'rzp_test_CLw7tH3O3P5eQM',
                'type' => 'razor_payment_method',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            12 =>
            array(
                'id' => 13,
                'name' => 'razorpay_publickey',
                'val' => 'rzp_test_CLw7tH3O3P5eQM',
                'type' => 'razor_payment_method',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            13 =>
            array(
                'id' => 14,
                'name' => 'str_payment_method',
                'val' => '1',
                'type' => 'stripePayment',
                'datatype' => 'payment_gateways',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            14 =>
            array(
                'id' => 15,
                'name' => 'stripe_secretkey',
                'val' => 'sk_test_CG2JhAIXvVWDeFUFqtUizO4N00zmvm7o8J',
                'type' => 'str_payment_method',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            15 =>
            array(
                'id' => 16,
                'name' => 'stripe_publickey',
                'val' => 'pk_test_HtQwwWoE9b43mfy5km6ThSPN00xunQv8J9',
                'type' => 'str_payment_method',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            16 =>
            array(
                'id' => 17,
                'name' => 'paystack_payment_method',
                'val' => '1',
                'type' => 'paystackPayment',
                'datatype' => 'payment_gateways',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            17 =>
            array(
                'id' => 18,
                'name' => 'paystack_secretkey',
                'val' => 'sk_test_9b5bf65070d9773c7a2b3aa7dd8d41310c5fc03c',
                'type' => 'paystack_payment_method',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            18 =>
            array(
                'id' => 19,
                'name' => 'paystack_publickey',
                'val' => 'pk_test_8c41a6f40d2753586db092fbe22320ac8eda874d',
                'type' => 'paystack_payment_method',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            19 =>
            array(
                'id' => 20,
                'name' => 'paypal_payment_method',
                'val' => '1',
                'type' => 'paypalPayment',
                'datatype' => 'payment_gateways',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            20 =>
            array(
                'id' => 21,
                'name' => 'paypal_secretkey',
                'val' => 'EGvqxtKeQIK5LIPbYLuWTMLoCtqzuoNaFUEvaltLlW2Ka58OwTg5fiv_Q',
                'type' => 'paypal_payment_method',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            21 =>
            array(
                'id' => 22,
                'name' => 'paypal_clientid',
                'val' => 'AepfSIAvfjV4DCulR7pzq2baaxjpkt0vcl0CBJt-YFKaQ6i7fwSY6LubCPtftIGXBX4elIvUL-aPyB2e',
                'type' => 'paypal_payment_method',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            22 =>
            array(
                'id' => 23,
                'name' => 'flutterwave_payment_method',
                'val' => '1',
                'type' => 'flutterwavePayment',
                'datatype' => 'payment_gateways',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            23 =>
            array(
                'id' => 24,
                'name' => 'flutterwave_secretkey',
                'val' => 'FLWSECK_TEST-76e58fc4d85dd2c3fc01ea7ef5b9e2bb-X',
                'type' => 'flutterwave_payment_method',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            24 =>
            array(
                'id' => 25,
                'name' => 'flutterwave_publickey',
                'val' => 'FLWPUBK_TEST-0e16d1deea10a74762ea18fd0bf5be1c-X',
                'type' => 'flutterwave_payment_method',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            25 =>
            array(
                'id' => 26,
                'name' => 'cinet_payment_method',
                'val' => '0',
                'type' => 'paymentcinet',
                'datatype' => 'payment_gateways',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            26 =>
            array(
                'id' => 27,
                'name' => 'sadad_payment_method',
                'val' => '0',
                'type' => 'paymentsadad',
                'datatype' => 'payment_gateways',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            27 =>
            array(
                'id' => 28,
                'name' => 'airtel_payment_method',
                'val' => '0',
                'type' => 'airtelpayment',
                'datatype' => 'payment_gateways',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            28 =>
            array(
                'id' => 29,
                'name' => 'phonepe_payment_method',
                'val' => '0',
                'type' => 'phonepepayment',
                'datatype' => 'payment_gateways',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            29 =>
            array(
                'id' => 30,
                'name' => 'midtrans_payment_method',
                'val' => '0',
                'type' => 'midtranspayment',
                'datatype' => 'payment_gateways',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),


            30 =>
            array(
                'id' => 31,
                'name' => 'is_social_login',
                'val' => '1',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            31 =>
            array(
                'id' => 32,
                'name' => 'is_google_login',
                'val' => '1',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            32 =>
            array(
                'id' => 33,
                'name' => 'is_otp_login',
                'val' => '1',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            33 =>
            array(
                'id' => 34,
                'name' => 'is_apple_login',
                'val' => '1',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            34 =>
            array(
                'id' => 35,
                'name' => 'is_firebase_notification',
                'val' => '1',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            35 =>
            array(
                'id' => 36,
                'name' => 'firebase_key',
                'val' => 'carilab-laravel-flutter',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            36 =>
            array(
                'id' => 37,
                'name' => 'is_user_push_notification',
                'val' => '1',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            37 =>
            array(
                'id' => 38,
                'name' => 'is_application_link',
                'val' => '1',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            38 =>
            array(
                'id' => 39,
                'name' => 'ios_url',
                'val' => 'https://www.iosurl.com',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            39 =>
            array(
                'id' => 40,
                'name' => 'android_url',
                'val' => 'https://www.androidurl.com',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            40 =>
            array(
                'id' => 41,
                'name' => 'force_update',
                'val' => '0',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            41 =>
            array(
                'id' => 42,
                'name' => 'app_version',
                'val' => null,
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            42 =>
            array(
                'id' => 43,
                'name' => 'is_ChatGPT_integration',
                'val' => '1',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            43 =>
            array(
                'id' => 44,
                'name' => 'ChatGPT_key',
                'val' => 'sk-proj-G6p2RGgra6qGWBaPcdBoT3BlbkFJ6HjS6Bonr4lI2ag0YtLE',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            44 =>
            array(
                'id' => 45,
                'name' => 'google_client_id',
                'val' => '215579898202-7vtk926nft9hc04acnesbk0mv8oroijv.apps.googleusercontent.com',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            45 =>
            array(
                'id' => 46,
                'name' => 'google_client_secret',
                'val' => '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',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            46 =>
            array(
                'id' => 47,
                'name' => 'google_redirect_uri',
                'val' => 'http://127.0.0.1:8000/auth/google/callback',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            47 =>
            array(
                'id' => 48,
                'name' => 'apiKey',
                'val' => 'AIzaSyBFQ9fiQoNoErlFUIP2Njh0Lj34pzAxyrs',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            48 =>
            array(
                'id' => 49,
                'name' => 'authDomain',
                'val' => 'carilab-laravel-flutter.firebaseapp.com',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            49 =>
            array(
                'id' => 50,
                'name' => 'databaseURL',
                'val' => 'https://carilab-laravel-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            50 =>
            array(
                'id' => 51,
                'name' => 'projectId',
                'val' => 'carilab-laravel-flutter',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            51 =>
            array(
                'id' => 52,
                'name' => 'storageBucket',
                'val' => 'carilab-laravel-flutter.appspot.com',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            52 =>
            array(
                'id' => 53,
                'name' => 'messagingSenderId',
                'val' => '215579898202',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            53 =>
            array(
                'id' => 54,
                'name' => 'appId',
                'val' => '1:215579898202:web:0f25cc0b276ee1c2e24363',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            54 =>
            array(
                'id' => 55,
                'name' => 'measurementId',
                'val' => 'G-V6YW8LYZ2G',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            55 =>
            array(
                'id' => 56,
                'name' => 'is_multi_vendor',
                'val' => '1',
                'type' => 'appconfig',
                'datatype' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            56 =>
            array(
                'id' => 57,
                'name' => 'logo',
                'val' => asset('img/logo/logo.png'),
                'type' => 'media',
                'datatype' => 'image',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:12:31',
                'updated_at' => '2024-08-08 10:12:31',
            ),
            57 =>
            array(
                'id' => 58,
                'name' => 'vendor_commission_type',
                'val' => 'global',
                'type' => 'commission',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            58 =>
            array(
                'id' => 59,
                'name' => 'collector_commission_type',
                'val' => 'global',
                'type' => 'commission',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:38:37',
                'updated_at' => '2024-08-08 10:38:37',
                'deleted_at' => NULL,
            ),
            59 =>
            array(
                'id' => 60,
                'name' => 'default_currency',
                'val' => '230',
                'type' => 'misc',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
            60 =>
            array(
                'id' => 61,
                'name' => 'currency_position',
                'val' => 'left',
                'type' => 'misc',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
            61 =>
            array(
                'id' => 62,
                'name' => 'date_format',
                'val' => 'd-m-Y',
                'type' => 'misc',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
            62 =>
            array(
                'id' => 63,
                'name' => 'time_format',
                'val' => 'H:i',
                'type' => 'misc',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
            63 =>
            array(
                'id' => 64,
                'name' => 'distance_type',
                'val' => 'km',
                'type' => 'misc',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
            64 =>
            array(
                'id' => 65,
                'name' => 'radious',
                'val' => '50',
                'type' => 'misc',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
            65 =>
            array(
                'id' => 66,
                'name' => 'digitafter_decimal_point',
                'val' => '2',
                'type' => 'misc',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
            66 =>
            array(
                'id' => 67,
                'name' => 'settings_copyright',
                'val' => 'carilab',
                'type' => 'misc',
                'datatype' => 'misc',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-08-08 10:31:01',
                'updated_at' => '2024-08-08 10:31:01',
                'deleted_at' => NULL,
            ),
        ));
        foreach ($data as $setting) {
            $service = Setting::create($setting);
        }
        $sourceFilePath = base_path('public/dummy-images/json-file/carilab-laravel-flutter-firebase-adminsdk-czzah-2c84a7b029.json');
        $destinationPath = storage_path('app/data/carilab-laravel-flutter-firebase-adminsdk-czzah-2c84a7b029.json');

        // Check if the file exists in the source location
        if (File::exists($sourceFilePath)) {
            // Ensure the destination directory exists
            if (!File::isDirectory(storage_path('app/data'))) {
                File::makeDirectory(storage_path('app/data'), 0755, true);
            }

            // Copy the file to the destination directory
            File::copy($sourceFilePath, $destinationPath);
            $this->command->info('Firebase JSON file has been copied successfully.');
        } else {
            $this->command->error('Firebase JSON file not found at ' . $sourceFilePath);
        }
    }
}
