<?php

namespace Database\Seeders\Auth;

use App\Events\Backend\UserCreated;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;
use App\Models\Address;
use Laravolt\Avatar\Facade as Avatar;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Modules\Collector\Models\Collector;
use Modules\Collector\Models\CollectorVendorMapping;
use Modules\Collector\Models\CollectorLabMapping;
use Modules\Wallet\Models\Wallet;
use Modules\Commision\Models\Commision;
/**
 * Class UserTableSeeder.
 */
class UserTableSeeder extends Seeder
{
    /**
     * Run the database seed.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();

        // Add the master administrator, user id of 1
        $avatarPath = config('app.avatar_base_path');
        if(env('IS_DUMMY_DATA')==false){

        $users = [
            [
                'first_name' => 'Super',
                'last_name' => 'Admin',
                'email' => 'superadmin@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-81859861',
                'date_of_birth' => fake()->date,
                'gender' => 'Male',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'admin',
                'address'=>'3 Elim Street, USA',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/admin/super_admin.png'),
                
            ],
            //admin
            [
                'first_name' => 'Ivan',
                'last_name' => 'Norris',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-74858414',
                'date_of_birth' => fake()->date,
                'gender' => 'Male',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'demo_admin',
                'address' => '5 Willow Drive Street, USA',  // Updated address
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/admin/demo_admin.png'),
             
            ],
        ];
        }else{
            $users = [
            [
                'first_name' => 'Super',
                'last_name' => 'Admin',
                'email' => 'superadmin@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-81859861',
                'date_of_birth' => fake()->date,
                'gender' => 'female',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'admin',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/admin/super_admin.png'),
                
            ],
            [
                'first_name' => 'Ivan',
                'last_name' => 'Norris',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-74858414',
                'date_of_birth' => fake()->date,
                'gender' => 'male',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'demo_admin',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/admin/demo_admin.png'),
             
            ],
            [
                'first_name' => 'John',
                'last_name' => 'Doe',
                'email' => 'john@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-45789525',
                'date_of_birth' => '1994-06-21',
                'login_type' => 'otp',
                'address' => '72 Willow Drive, USA',
                'gender' => 'male',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/vendors/liam.png'),
            ],
            [
                'first_name' => 'Liam',
                'last_name' => 'Long',
                'username' => 'liam_long',
                'email' => 'vendor@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-85749651',
                'date_of_birth' => '1986-05-07',
                'gender' => 'male',
                'address' => '12, Blueberry Lane, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'vendor',
                'is_subscribe' => 1,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'is_available' => 1,
                'image' => public_path('/dummy-images/profile/vendors/liam.png'),
            ],
            [
                'first_name' => 'Susan',
                'last_name' => 'Williams',
                'username' => 'susan_williams',
                'email' => 'susan@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-23815478',
                'date_of_birth' => '1984-10-05',
                'gender' => 'female',
                'address' => '76, Spruce Avenue, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'vendor',
                'is_subscribe' => 1,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'is_available' => 1,
                'image' => public_path('/dummy-images/profile/vendors/susan.png'),
            ],
            [
                'first_name' => 'Roberto',
                'last_name' => 'Gorden',
                'username' => 'roberto_gorden',
                'email' => 'roberto@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-12415478',
                'date_of_birth' => '1982-01-12',
                'gender' => 'male',
                'address' => '31, Lakeview Drive, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'vendor',
                'is_subscribe' => 1,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/vendors/roberto.png'),
            ],
            [
                'first_name' => 'Richard',
                'last_name' => 'Howard',
                'username' => 'richard_howard',
                'email' => 'richard@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-81547856',
                'date_of_birth' => '1990-06-21',
                'gender' => 'male',
                'address' => '90, Highland Road, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'vendor',
                'is_subscribe' => 1,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/vendors/richard.png'),
            ],
              [
                'first_name' => 'Ken',
                'last_name' => 'Simon',
                'username' => 'ken_simon',
                'email' => 'ken@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-74841458',
                'date_of_birth' => '1989-04-04',
                'gender' => 'male',
                'address' => '2, Aspen Street, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'vendor',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/vendors/ken.png'),
                
            ],
            [
                'first_name' => 'Deborah',
                'last_name' => 'Thomas',
                'username' => 'deborah_thomas',
                'email' => 'deborah@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-15478605',
                'date_of_birth' => '1992-01-29',
                'gender' => 'female',
                'address' => '6, Willow Court, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'vendor',
                'is_subscribe' => 1,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/vendors/deborah.png'),
                
            ],

        //user data
            [
                'first_name' => 'Robert',
                'last_name' => 'Martin',
                'username' => 'robert_martin',
                'email' => 'robert@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-74961545',
                'date_of_birth' => '1964-10-05',
                'gender' => 'male',
                'address' => '10 Elm Street, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/robert.png'),
            ],
            [
                'first_name' => 'Bentley',
                'last_name' => 'Howard',
                'username' => 'bentley_howard',
                'email' => 'bentley@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-25987448',
                'date_of_birth' => '2001-01-19',
                'gender' => 'male',
                'address' => '42 Oakwood Avenue, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/bentley.png'),
            ],
            [
                'first_name' => 'Brian',
                'last_name' => 'Shaw',
                'username' => 'brian_shaw',
                'email' => 'brian@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-65478912',
                'date_of_birth' => '1990-01-20',
                'gender' => 'male',
                'address' => '82 Pinecrest Lane, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/brian.png'),
            ],
            [
                'first_name' => 'Gilbert',
                'last_name' => 'Adams',
                'username' => 'gilbert_adams',
                'email' => 'gilbert@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-74587110',
                'date_of_birth' => '1969-08-03',
                'gender' => 'male',
                'address' => '49 Maple Street, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/gilbert.png'),
            ],
            [
                'first_name' => 'Pedra',
                'last_name' => 'Danlel',
                'username' => 'pedra_danlel',
                'email' => 'pedra@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-65841258',
                'date_of_birth' => '1981-09-25',
                'gender' => 'female',
                'address' => '35 Redwood Road, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/pedra.png'),
            ],
            [
                'first_name' => 'Diana',
                'last_name' => 'Norris',
                'username' => 'diana_norris',
                'email' => 'diana@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-56874125',
                'date_of_birth' => '1997-03-07',
                'gender' => 'female',
                'address' => '59 Cedar Lane, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/diana.png'),
            ],
            [
                'first_name' => 'Stella',
                'last_name' => 'Green',
                'username' => 'stella_green',
                'email' => 'stella@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-63897456',
                'date_of_birth' => '1998-07-09',
                'gender' => 'female',
                'address' => '22 Birch Street, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/stella.png'),
            ],
            [
                'first_name' => 'Lisa',
                'last_name' => 'Lucas',
                'username' => 'lisa_lucas',
                'email' => 'lisa@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-36524195',
                'date_of_birth' => '1991-04-30',
                'gender' => 'female',
                'address' => '9 Cherry Avenue, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/lisa.png'),
                
            ],
            [
                'first_name' => 'Tristan',
                'last_name' => 'Erickson',
                'username' => 'tristan_erickson',
                'email' => 'tristan@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-47525545',
                'date_of_birth' => '1984-10-13',
                'gender' => 'male',
                'address' => '25 Oakwood Lane, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/tristan.png'),
                
            ],
            [
                'first_name' => 'Emily',
                'last_name' => 'Parks',
                'username' => 'emily_parks',
                'email' => 'emily@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-35178545',
                'date_of_birth' => '1982-01-06',
                'gender' => 'female',
                'address' => '36 Meadowbrook Drive, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/emily.png'),
            ],
            [
                'first_name' => 'Oscar',
                'last_name' => 'Miles',
                'username' => 'oscar_miles',
                'email' => 'oscar@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-55247857',
                'date_of_birth' => '1990-06-10',
                'gender' => 'male',
                'address' => '11 Sunset Boulevard, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/oscar.png'),
                
            ],
            [
                'first_name' => 'Tracy',
                'last_name' => 'Jones',
                'username' => 'tracy_jones',
                'email' => 'tracy@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-49025523',
                'date_of_birth' => '1989-04-21',
                'gender' => 'female',
                'address' => '65 Magnolia Avenue, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/tracy.png'),
            ],
            [
                'first_name' => 'Vernon',
                'last_name' => 'Simon',
                'username' => 'vernon_simon',
                'email' => 'vernon@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-45154569',
                'date_of_birth' => '1989-04-03',
                'gender' => 'male',
                'address' => '86, Riverside Drive, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/vernon.png'),
            ],
            [
                'first_name' => 'Alexis',
                'last_name' => 'Evans',
                'username' => 'alexis_evans',
                'email' => 'alexis@gmail.com',
                'password' => Hash::make('12345678'),
                'mobile' => '1-25678570',
                'date_of_birth' => '1994-07-13',
                'gender' => 'male',
                'address' => '2, Oakwood Main Lane, USA',
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'user',
                'is_subscribe' => 0,
                'education' => '',
                'degree' => '',
                'experience' => '',
                'image' => public_path('/dummy-images/profile/patients/alexis.png'),
            ],

        //collector data

            [
                'image' => public_path('/dummy-images/profile/collectors/felix.png'),
                'first_name' => 'Felix',
                'last_name' => 'Harris',
                'username' => 'felix_harris',
                'email' => 'collector@gmail.com',
                'mobile' => '1-78952526',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1984-10-19',
                'gender' => 'male',
                'vendor_id' => 4,
                'lab_id' => 1,
                'education' => 'University of California, Los Angeles (UCLA)',
                'degree' => 'Bachelor\'s in Biological Sciences',
                'experience' => '3 years in clinical sample collection',
                'status' => 1,
                'address' => '6 Heart Street, Cityville, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
                'is_available' => 1,
            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/jorge.png'),
                'first_name' => 'Jorge',
                'last_name' => 'Perez',
                'username' => 'jorge_perez',
                'email' => 'jorge@gmail.com',
                'mobile' => '1-85961589',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1982-01-05',
                'gender' => 'male',
                'vendor_id' => 5,
                'lab_id' => 4,
                'education' => 'University of Texas at Austin',
                'degree' => 'Bachelor\'s in Biomedical Sciences',
                'experience' => '4 years in pathology labs',
                'status' => 1,
                'address' => '48, Tooth Street, Townsville, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
                'is_available' => 1,
            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/erica.png'),
                'first_name' => 'Erica',
                'last_name' => 'Mendiz',
                'username' => 'erica_mendiz',
                'email' => 'erica@gmail.com',
                'mobile' => '1-45765541',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1990-06-08',
                'gender' => 'female',
                'vendor_id' => 6,
                'lab_id' => 5,
                'education' => 'University of Florida',
                'degree' => 'Bachelor\'s in Medical Laboratory Technology',
                'experience' => '5 years in diagnostic sample handling',
                'status' => 1,
                'address' => '9, Harmony Road, Healthtown, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/parsa.png'),
                'first_name' => 'Parsa',
                'last_name' => 'Evana',
                'username' => 'parsa_evana',
                'email' => 'parsa@gmail.com',
                'mobile' => '1-56745852',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1989-04-16',
                'gender' => 'female',
                'vendor_id' => 7,
                'lab_id' => 7,
                'education' => 'New York University (NYU)',
                'degree' => 'Bachelor\'s in Public Health',
                'experience' => '2 years as a phlebotomist',
                'status' => 1,
                'address' => '101, Dental Avenue, Smilesville, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/daniel.png'),
                'first_name' => 'Daniel',
                'last_name' => 'Wiliams',
                'username' => 'daniel_wiliams',
                'email' => 'daniel@gmail.com',
                'mobile' => '1-25987415',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1989-04-28',
                'gender' => 'male',
                'vendor_id' => 9,
                'lab_id' => 8,
                'education' => 'Harvard University',
                'degree' => 'Master\'s in Medical Laboratory Science',
                'experience' => '6 years in advanced sample analysis',
                'status' => 1,
                'address' => '23, Vision Way, Seecity, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/harvey.png'),
                'first_name' => 'Harvey',
                'last_name' => 'Francis',
                'username' => 'harvey_francis',
                'email' => 'harvey@gmail.com',
                'mobile' => '1-45789655',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1994-07-02',
                'gender' => 'male',
                'vendor_id' => 4,
                'lab_id' => 2,
                'education' => 'University of Michigan',
                'degree' => 'Bachelor\'s in Clinical Laboratory Science',
                'experience' => '3 years in laboratory management',
                'status' => 1,
                'address' => '56, Main Street, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
                'is_available' => 1,
            ],           
            [
                'image' => public_path('/dummy-images/profile/collectors/angela.png'),
                'first_name' => 'Angela',
                'last_name' => 'Perez',
                'username' => 'angela_perez',
                'email' => 'angela@gmail.com',
                'mobile' => '1-56587152',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1990-09-20',
                'gender' => 'female',
                'vendor_id' => 6,
                'lab_id' => 6,
                'education' => 'Stanford University',
                'degree' => 'Bachelor’s in Health Science',
                'experience' => '4 years in sample logistics',
                'status' => 1,
                'address' => '12, Oak Avenue, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
                'is_available' => 1,
            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/amy.png'),
                'first_name' => 'Amy',
                'last_name' => 'Ellis',
                'username' => 'amy_ellis',
                'email' => 'amy@gmail.com',
                'mobile' => '1-63987415',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1989-01-21',
                'gender' => 'female',
                'vendor_id' => 4,
                'lab_id' => 3,
                'education' => 'University of North Carolina at Chapel Hill',
                'degree' => 'Bachelor’s in Microbiology',
                'experience' => '2 years in specimen processing',
                'status' => 1,
                'address' => '63, Elm Street, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
                'is_available' => 1,
            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/miles.png'),
                'first_name' => 'Miles',
                'last_name' => 'Warren',
                'username' => 'miles_warren',
                'email' => 'miles@gmail.com',
                'mobile' => '1-47125589',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1981-09-09',
                'gender' => 'male',
                'vendor_id' => 4,
                'lab_id' => 1,
                'education' => 'Johns Hopkins University',
                'degree' => 'Master’s in Public Health',
                'experience' => '7 years in clinical research',
                'status' => 1,
                'address' => '56, Main Street, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',

            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/karen.png'),
                'first_name' => 'Karen',
                'last_name' => 'Scott',
                'username' => 'karen_scottt',
                'email' => 'karen@gmail.com',
                'mobile' => '1-25851498',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1997-03-15',
                'gender' => 'female',
                'vendor_id' => 5,
                'lab_id' => 4,
                'education' => 'University of Washington',
                'degree' => 'Bachelor’s in Laboratory Medicine',
                'experience' => '5 years in field sample collections',
                'status' => 1,
                'address' => '12, Oak Avenue, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/glen.png'),
                'first_name' => 'Glen',
                'last_name' => 'Hamiltor',
                'username' => 'glen_hamiltor',
                'email' => 'glen@gmail.com',
                'mobile' => '1-55415857',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1998-07-13',
                'gender' => 'male',
                'vendor_id' => 4,
                'lab_id' => 2,
                'education' => 'University of Chicago',
                'degree' => 'Bachelor’s in Biochemistry',
                'experience' => '3 years in home sample collection',
                'status' => 1,
                'address' => '63, Elm Street, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/jessica.png'),
                'first_name' => 'Jessica',
                'last_name' => 'Nelson',
                'username' => 'jessica_nelson',
                'email' => 'jessica@gmail.com',
                'mobile' => '1-52547855',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1991-04-27',
                'gender' => 'female',
                'education' => 'Boston University',
                'degree' => 'Bachelor’s in Biochemistry',
                'experience' => '4 years in sample preparation',
                'status' => 1,
                'address' => '47, Pine Road, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
                'vendor_id' => 6,
                'lab_id' => 5,
            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/julian.png'),
                'first_name' => 'Julian',
                'last_name' => 'Fisher',
                'username' => 'julian_fisher',
                'email' => 'julian@gmail.com',
                'mobile' => '1-15478568',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1984-10-07',
                'gender' => 'male',
                'vendor_id' => 7,
                'lab_id' => 7,
                'education' => 'University of Pennsylvania',
                'degree' => 'Master’s in Medical Technology',
                'experience' => '6 years in clinical lab diagnostics',
                'status' => 0,
                'address' => '153, Cedar Lane, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',

            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/joey.png'),
                'first_name' => 'Joey',
                'last_name' => 'Butler',
                'username' => 'joey_butler',
                'email' => 'joey@gmail.com',
                'mobile' => '1-78847855',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '2001-01-10',
                'gender' => 'male',
                'vendor_id' => 9,
                'lab_id' => 8,
                'education' => 'Duke University',
                'degree' => 'Bachelor’s in Health and Human Services',
                'experience' => '2 years in mobile laboratory units',
                'status' => 0,
                'address' => '63, Elm Hill Street, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
                'is_available' => 1,
            ],
            [
                'image' => public_path('/dummy-images/profile/collectors/hanna.png'),
                'first_name' => 'Hanna',
                'last_name' => 'Rivera',
                'username' => 'hanna_rivera',
                'email' => 'hanna@gmail.com',
                'mobile' => '1-45965541',
                'password' => Hash::make('12345678'),
                'date_of_birth' => '1990-01-31', // Converted to YYYY-MM-DD format
                'gender' => 'female',
                'education' => 'Columbia University',
                'degree' => 'Bachelor’s in Biology and Chemistry',
                'experience' => '3 years in patient sample collection',
                'status' => 0, // Assuming "Active" means 1 (Active status)
                'address' => '56, Main Wing Street, USA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_type' => 'collector',
                'is_available' => 1,
                'vendor_id' => 4,
                'lab_id' => 3,
            ],

        ];                                        
        } 

        


        if (env('IS_DUMMY_DATA')) {
            foreach ($users as $key => $user_data) {

                $logo = $user_data['image'] ?? null;
                $userData = Arr::except($user_data, ['image','title','user_id','amount','vendor_id','lab_id','education','degree','experience']);
                $user = User::create($userData);
                if (isset($logo)) {
                    $this->attachFeatureImage($user, $logo);
                }
           
                $user->assignRole($user->user_type);
                event(new UserCreated($user));
                $user->save();
                if($user->user_type ='collector'){
                    Collector::create([
                        'user_id' => $user->id,
                        'education' => $user_data['education'],
                        'degree' => $user_data['degree'],
                        'experience' => $user_data['experience'],
                    ]);
                   if(!empty($user_data['vendor_id'])){
                        CollectorVendorMapping::create([
                            'vendor_id' => $user_data['vendor_id'],
                            'collector_id' => $user->id,
                        ]);
                    }
                    if(!empty($user_data['lab_id'])){
                        CollectorLabMapping::create([
                            'lab_id' => $user_data['lab_id'],
                            'collector_id' => $user->id,
                        ]);
                    }
                }
                $user_data['title'] = $user_data['first_name'] . ' ' . $user_data['last_name'];
                $user_data['amount'] = $user_data['amount'] ?? 0;

               
                if($user_data['user_type'] =='user' || $user_data['user_type'] =='vendor' || $user_data['user_type'] =='collector') {
                    $wallet=Wallet::create([
                        'user_id' => $user->id,
                        'title' => $user_data['title'],
                        'amount' => $user_data['amount'],
                    ]);
                }
            }
            Commision::insert([
                [    
                    'title'=>'Volume-Based Commission',
                    'type'=>'Fixed',
                    'value'=>5,
                    'user_type'=>'collector',
                    'status'=>1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'title'=>'Performance-Based Commission',
                    'type'=>'Percentage',
                    'value'=>40,
                    'user_type'=>'collector',
                    'status'=>1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'title'=>'Flat Percentage-Based Commission',
                    'type'=>'Fixed',
                    'value'=>5,
                    'user_type'=>'vendor',
                    'status'=>1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'title'=>'Tiered Commission',
                    'type'=>'Percentage',
                    'value'=>30,
                    'user_type'=>'vendor',
                    'status'=>1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);
            
            Schema::enableForeignKeyConstraints();
        }
    }





    private function attachFeatureImage($model, $publicPath)
    {

        $file = new \Illuminate\Http\File($publicPath);

        $media = $model->addMedia($file)->preservingOriginal()->toMediaCollection('profile_image');

        return $media;

    }

}
