<?php

namespace Modules\Appointment\database\seeders;

use Illuminate\Database\Seeder;

class AppointmentTransactionTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('appointment_transaction')->delete();
        
        \DB::table('appointment_transaction')->insert(array (
            0 => 
            array (
                'id' => 1,
                'appointment_id' => 1,
                'txn_id' => 'pay_Q8clFZfqtMoOzl',
                'discount_type' => 'fixed',
                'discount_value' => 10.0,
                'discount_amount' => 10.0,
                'coupon_id' => 3,
                'coupon' => '{"id":3,"vendor_id":null,"lab_id":1,"coupon_code":"QWE78TYL","discount_type":"fixed","discount_value":"50.00","applicability":"specific_packages","start_at":"2025-02-19","end_at":"2025-04-05","total_usage_limit":12,"per_customer_usage_limit":3,"status":true,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2025-03-19T09:43:22.000000Z","updated_at":"2025-03-19T09:43:22.000000Z","deleted_at":null,"feature_image":"https:\\/\\/dummyimage.com\\/600x300\\/cfcfcf\\/000000.png","media":[]}',
                'coupon_amount' => 50.0,
                'tax' => '"[{\\"id\\":1,\\"title\\":\\"Service Tax\\",\\"value\\":5,\\"type\\":\\"Percentage\\",\\"status\\":1},{\\"id\\":2,\\"title\\":\\"Home Collection Fee\\",\\"value\\":10,\\"type\\":\\"Fixed\\",\\"status\\":1}]"
',
                'total_tax_amount' => 11.9,
                'total_amount' => 451.9,
                'payment_type' => 'razorpay',
                'payment_status' => 'paid',
                'request_token' => NULL,
                'created_at' => '2025-03-19 15:23:11',
                'updated_at' => '2025-03-19 16:28:00',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'appointment_id' => 2,
                'txn_id' => NULL,
                'discount_type' => 'percentage',
                'discount_value' => 20.0,
                'discount_amount' => 80.0,
                'coupon_id' => NULL,
                'coupon' => NULL,
                'coupon_amount' => 0.0,
                'tax' => '"[{\\"id\\":1,\\"title\\":\\"Service Tax\\",\\"value\\":5,\\"type\\":\\"Percentage\\",\\"status\\":1},{\\"id\\":2,\\"title\\":\\"Home Collection Fee\\",\\"value\\":10,\\"type\\":\\"Fixed\\",\\"status\\":1}]"
',
                'total_tax_amount' => 11.9,
                'total_amount' => 331.9,
                'payment_type' => NULL,
                'payment_status' => 'pending',
                'request_token' => NULL,
                'created_at' => '2025-03-19 15:41:20',
                'updated_at' => '2025-03-19 15:41:20',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'appointment_id' => 3,
                'txn_id' => 'pi_1R4LCvFTMa5P8ht0Yd9TzYm8',
                'discount_type' => '',
                'discount_value' => 0.0,
                'discount_amount' => 0.0,
                'coupon_id' => NULL,
                'coupon' => NULL,
                'coupon_amount' => 0.0,
                'tax' => '"[{\\"id\\":1,\\"title\\":\\"Service Tax\\",\\"value\\":5,\\"type\\":\\"Percentage\\",\\"status\\":1},{\\"id\\":2,\\"title\\":\\"Home Collection Fee\\",\\"value\\":10,\\"type\\":\\"Fixed\\",\\"status\\":1}]"',
                'total_tax_amount' => 11.9,
                'total_amount' => 141.9,
                'payment_type' => 'stripe',
                'payment_status' => 'paid',
                'request_token' => NULL,
                'created_at' => '2025-03-19 15:47:27',
                'updated_at' => '2025-03-19 17:30:06',
                'deleted_at' => '2025-03-19 17:30:06',
            ),
            3 => 
            array (
                'id' => 4,
                'appointment_id' => 4,
                'txn_id' => NULL,
                'discount_type' => '',
                'discount_value' => 0.0,
                'discount_amount' => 0.0,
                'coupon_id' => NULL,
                'coupon' => NULL,
                'coupon_amount' => 0.0,
                'tax' => '"[{\\"id\\":1,\\"title\\":\\"Service Tax\\",\\"value\\":5,\\"type\\":\\"Percentage\\",\\"status\\":1},{\\"id\\":2,\\"title\\":\\"Home Collection Fee\\",\\"value\\":10,\\"type\\":\\"Fixed\\",\\"status\\":1}]"',
                'total_tax_amount' => 11.9,
                'total_amount' => 71.9,
                'payment_type' => 'cash',
                'payment_status' => 'send_to_vendor',
                'request_token' => NULL,
                'created_at' => '2025-03-19 15:49:01',
                'updated_at' => '2025-03-19 17:16:01',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'appointment_id' => 5,
                'txn_id' => NULL,
                'discount_type' => 'percentage',
                'discount_value' => 7.0,
                'discount_amount' => 14.0,
                'coupon_id' => NULL,
                'coupon' => NULL,
                'coupon_amount' => 0.0,
                'tax' => '"[{\\"id\\":1,\\"title\\":\\"Service Tax\\",\\"value\\":5,\\"type\\":\\"Percentage\\",\\"status\\":1},{\\"id\\":2,\\"title\\":\\"Home Collection Fee\\",\\"value\\":10,\\"type\\":\\"Fixed\\",\\"status\\":1}]"',
                'total_tax_amount' => 11.9,
                'total_amount' => 197.9,
                'payment_type' => NULL,
                'payment_status' => 'pending',
                'request_token' => NULL,
                'created_at' => '2025-03-19 15:49:41',
                'updated_at' => '2025-03-19 15:49:41',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'appointment_id' => 6,
                'txn_id' => NULL,
                'discount_type' => 'percentage',
                'discount_value' => 10.0,
                'discount_amount' => 50.0,
                'coupon_id' => NULL,
                'coupon' => NULL,
                'coupon_amount' => 0.0,
                'tax' => '"[{\\"id\\":1,\\"title\\":\\"Service Tax\\",\\"value\\":5,\\"type\\":\\"Percentage\\",\\"status\\":1},{\\"id\\":2,\\"title\\":\\"Home Collection Fee\\",\\"value\\":10,\\"type\\":\\"Fixed\\",\\"status\\":1}]"',
                'total_tax_amount' => 11.9,
                'total_amount' => 461.9,
                'payment_type' => NULL,
                'payment_status' => 'pending',
                'request_token' => NULL,
                'created_at' => '2025-03-19 15:51:04',
                'updated_at' => '2025-03-19 15:51:04',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'appointment_id' => 7,
                'txn_id' => NULL,
                'discount_type' => '',
                'discount_value' => 0.0,
                'discount_amount' => 0.0,
                'coupon_id' => NULL,
                'coupon' => NULL,
                'coupon_amount' => 0.0,
                'tax' => '"[{\\"id\\":1,\\"title\\":\\"Service Tax\\",\\"value\\":5,\\"type\\":\\"Percentage\\",\\"status\\":1},{\\"id\\":2,\\"title\\":\\"Home Collection Fee\\",\\"value\\":10,\\"type\\":\\"Fixed\\",\\"status\\":1}]"',
                'total_tax_amount' => 11.9,
                'total_amount' => 161.9,
                'payment_type' => NULL,
                'payment_status' => 'pending',
                'request_token' => NULL,
                'created_at' => '2025-03-19 15:51:45',
                'updated_at' => '2025-03-19 15:51:45',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'appointment_id' => 8,
                'txn_id' => NULL,
                'discount_type' => '',
                'discount_value' => 0.0,
                'discount_amount' => 0.0,
                'coupon_id' => NULL,
                'coupon' => NULL,
                'coupon_amount' => 0.0,
                'tax' => '"[{\\"id\\":1,\\"title\\":\\"Service Tax\\",\\"value\\":5,\\"type\\":\\"Percentage\\",\\"status\\":1},{\\"id\\":2,\\"title\\":\\"Home Collection Fee\\",\\"value\\":10,\\"type\\":\\"Fixed\\",\\"status\\":1}]"',
                'total_tax_amount' => 11.9,
                'total_amount' => 61.9,
                'payment_type' => NULL,
                'payment_status' => 'pending',
                'request_token' => NULL,
                'created_at' => '2025-03-19 15:55:21',
                'updated_at' => '2025-03-19 15:55:21',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'appointment_id' => 9,
                'txn_id' => 'pi_1R4LCvFTMa5P8ht0Yd9TzYm8',
                'discount_type' => '',
                'discount_value' => 0.0,
                'discount_amount' => 0.0,
                'coupon_id' => NULL,
                'coupon' => NULL,
                'coupon_amount' => 0.0,
                'tax' => '"[{\\"id\\":1,\\"title\\":\\"Service Tax\\",\\"value\\":5,\\"type\\":\\"Percentage\\",\\"status\\":1},{\\"id\\":2,\\"title\\":\\"Home Collection Fee\\",\\"value\\":10,\\"type\\":\\"Fixed\\",\\"status\\":1}]"',
                'total_tax_amount' => 11.9,
                'total_amount' => 141.9,
                'payment_type' => 'stripe',
                'payment_status' => 'paid',
                'request_token' => NULL,
                'created_at' => '2025-03-19 17:30:06',
                'updated_at' => '2025-03-19 17:30:06',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'appointment_id' => 10,
                'txn_id' => 'pi_1R4LgDFTMa5P8ht0Xn7JgwBO',
                'discount_type' => '',
                'discount_value' => 0.0,
                'discount_amount' => 0.0,
                'coupon_id' => NULL,
                'coupon' => NULL,
                'coupon_amount' => 0.0,
                'tax' => '"[{\\"id\\":1,\\"title\\":\\"Service Tax\\",\\"value\\":5,\\"type\\":\\"Percentage\\",\\"status\\":1},{\\"id\\":2,\\"title\\":\\"Home Collection Fee\\",\\"value\\":10,\\"type\\":\\"Fixed\\",\\"status\\":1},{\\"id\\":3,\\"title\\":\\"State Health Tax\\",\\"value\\":2,\\"type\\":\\"Percentage\\",\\"status\\":1}]"',
                'total_tax_amount' => 31.0,
                'total_amount' => 331.0,
                'payment_type' => 'stripe',
                'payment_status' => 'paid',
                'request_token' => NULL,
                'created_at' => '2025-03-19 17:49:26',
                'updated_at' => '2025-03-19 17:56:20',
                'deleted_at' => '2025-03-19 17:56:20',
            ),
            10 => 
            array (
                'id' => 11,
                'appointment_id' => 11,
                'txn_id' => 'pi_1R4LgDFTMa5P8ht0Xn7JgwBO',
                'discount_type' => '',
                'discount_value' => 0.0,
                'discount_amount' => 0.0,
                'coupon_id' => NULL,
                'coupon' => NULL,
                'coupon_amount' => 0.0,
                'tax' => '"[{\\"id\\":1,\\"title\\":\\"Service Tax\\",\\"value\\":5,\\"type\\":\\"Percentage\\",\\"status\\":1},{\\"id\\":2,\\"title\\":\\"Home Collection Fee\\",\\"value\\":10,\\"type\\":\\"Fixed\\",\\"status\\":1},{\\"id\\":3,\\"title\\":\\"State Health Tax\\",\\"value\\":2,\\"type\\":\\"Percentage\\",\\"status\\":1}]"',
                'total_tax_amount' => 31.0,
                'total_amount' => 331.0,
                'payment_type' => 'stripe',
                'payment_status' => 'paid',
                'request_token' => NULL,
                'created_at' => '2025-03-19 17:56:20',
                'updated_at' => '2025-03-19 17:56:20',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}