<?php

namespace Modules\Appointment\database\seeders;

use Illuminate\Database\Seeder;

class AppointmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('appointments')->delete();
        
        \DB::table('appointments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'status' => 'completed',
                'customer_id' => 3,
                'other_member_id' => NULL,
                'vendor_id' => 4,
                'lab_id' => 1,
                'test_id' => 1,
                'test_type' => 'test_package',
                'address_id' => -1,
                'appointment_date' => '2025-03-19',
                'appointment_time' => '16:30:00',
                'amount' => 500.0,
                'test_discount_amount' => 440.0,
                'collection_type' => 'lab',
                'total_amount' => 451.9,
                'submission_status' => 'accept',
                'test_case_status' => 'report_generated',
                'rejected_id' => NULL,
                'by_suggestion' => 0,
                'cancellation_reason' => NULL,
                'symptoms' => 'Breathing issues',
                'reschedule_reason' => NULL,
                'created_by' => 3,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-03-19 15:23:11',
                'updated_at' => '2025-03-19 16:46:12',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'status' => 'pending',
                'customer_id' => 21,
                'other_member_id' => NULL,
                'vendor_id' => 4,
                'lab_id' => 3,
                'test_id' => 9,
                'test_type' => 'test_package',
                'address_id' => -1,
                'appointment_date' => '2025-03-19',
                'appointment_time' => '16:30:00',
                'amount' => 400.0,
                'test_discount_amount' => 320.0,
                'collection_type' => 'lab',
                'total_amount' => 331.9,
                'submission_status' => 'pending',
                'test_case_status' => NULL,
                'rejected_id' => NULL,
                'by_suggestion' => 0,
                'cancellation_reason' => NULL,
                'symptoms' => 'Sore throat',
                'reschedule_reason' => NULL,
                'created_by' => 21,
                'updated_by' => 21,
                'deleted_by' => NULL,
                'created_at' => '2025-03-19 15:41:20',
                'updated_at' => '2025-03-19 15:41:20',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'status' => 'completed',
                'customer_id' => 21,
                'other_member_id' => NULL,
                'vendor_id' => 6,
                'lab_id' => 6,
                'test_id' => 162,
                'test_type' => 'test_case',
                'address_id' => 1,
                'appointment_date' => '2025-03-19',
                'appointment_time' => '16:30:00',
                'amount' => 130.0,
                'test_discount_amount' => 130.0,
                'collection_type' => 'home',
                'total_amount' => 141.9,
                'submission_status' => 'reject',
                'test_case_status' => NULL,
                'rejected_id' => NULL,
                'by_suggestion' => 0,
                'cancellation_reason' => NULL,
                'symptoms' => 'Fever',
                'reschedule_reason' => NULL,
                'created_by' => 21,
                'updated_by' => 1,
                'deleted_by' => 1,
                'created_at' => '2025-03-19 15:47:27',
                'updated_at' => '2025-03-19 17:30:06',
                'deleted_at' => '2025-03-19 17:30:06',
            ),
            3 => 
            array (
                'id' => 4,
                'status' => 'completed',
                'customer_id' => 3,
                'other_member_id' => NULL,
                'vendor_id' => 4,
                'lab_id' => 2,
                'test_id' => 198,
                'test_type' => 'test_case',
                'address_id' => 2,
                'appointment_date' => '2025-03-19',
                'appointment_time' => '16:30:00',
                'amount' => 60.0,
                'test_discount_amount' => 60.0,
                'collection_type' => 'home',
                'total_amount' => 71.9,
                'submission_status' => 'pending',
                'test_case_status' => NULL,
                'rejected_id' => NULL,
                'by_suggestion' => 0,
                'cancellation_reason' => NULL,
                'symptoms' => 'Cold & Flu',
                'reschedule_reason' => NULL,
                'created_by' => 3,
                'updated_by' => 29,
                'deleted_by' => NULL,
                'created_at' => '2025-03-19 15:49:01',
                'updated_at' => '2025-03-19 17:08:20',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'status' => 'pending',
                'customer_id' => 3,
                'other_member_id' => NULL,
                'vendor_id' => 4,
                'lab_id' => 2,
                'test_id' => 7,
                'test_type' => 'test_package',
                'address_id' => -1,
                'appointment_date' => '2025-03-19',
                'appointment_time' => '17:00:00',
                'amount' => 200.0,
                'test_discount_amount' => 186.0,
                'collection_type' => 'lab',
                'total_amount' => 197.9,
                'submission_status' => 'pending',
                'test_case_status' => NULL,
                'rejected_id' => NULL,
                'by_suggestion' => 0,
                'cancellation_reason' => NULL,
                'symptoms' => 'Skin Rash',
                'reschedule_reason' => NULL,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2025-03-19 15:49:41',
                'updated_at' => '2025-03-19 15:49:41',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'status' => 'pending',
                'customer_id' => 3,
                'other_member_id' => NULL,
                'vendor_id' => 4,
                'lab_id' => 3,
                'test_id' => 10,
                'test_type' => 'test_package',
                'address_id' => -1,
                'appointment_date' => '2025-03-19',
                'appointment_time' => '17:00:00',
                'amount' => 500.0,
                'test_discount_amount' => 450.0,
                'collection_type' => 'lab',
                'total_amount' => 461.9,
                'submission_status' => 'pending',
                'test_case_status' => NULL,
                'rejected_id' => NULL,
                'by_suggestion' => 0,
                'cancellation_reason' => NULL,
                'symptoms' => 'Breathing issues',
                'reschedule_reason' => NULL,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2025-03-19 15:51:04',
                'updated_at' => '2025-03-19 15:51:04',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'status' => 'pending',
                'customer_id' => 3,
                'other_member_id' => NULL,
                'vendor_id' => 4,
                'lab_id' => 2,
                'test_id' => 196,
                'test_type' => 'test_case',
                'address_id' => 2,
                'appointment_date' => '2025-03-19',
                'appointment_time' => '16:00:00',
                'amount' => 150.0,
                'test_discount_amount' => 150.0,
                'collection_type' => 'home',
                'total_amount' => 161.9,
                'submission_status' => 'pending',
                'test_case_status' => NULL,
                'rejected_id' => NULL,
                'by_suggestion' => 0,
                'cancellation_reason' => NULL,
                'symptoms' => 'Body Pain',
                'reschedule_reason' => NULL,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2025-03-19 15:51:45',
                'updated_at' => '2025-03-19 15:51:45',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'status' => 'pending',
                'customer_id' => 3,
                'other_member_id' => NULL,
                'vendor_id' => 4,
                'lab_id' => 2,
                'test_id' => 201,
                'test_type' => 'test_case',
                'address_id' => 2,
                'appointment_date' => '2025-03-19',
                'appointment_time' => '17:30:00',
                'amount' => 50.0,
                'test_discount_amount' => 50.0,
                'collection_type' => 'home',
                'total_amount' => 61.9,
                'submission_status' => 'pending',
                'test_case_status' => NULL,
                'rejected_id' => NULL,
                'by_suggestion' => 0,
                'cancellation_reason' => NULL,
                'symptoms' => 'Lower abdominal pain',
                'reschedule_reason' => NULL,
                'created_by' => 3,
                'updated_by' => 3,
                'deleted_by' => NULL,
                'created_at' => '2025-03-19 15:55:21',
                'updated_at' => '2025-03-19 15:55:21',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'status' => 'accept',
                'customer_id' => 21,
                'other_member_id' => NULL,
                'vendor_id' => 6,
                'lab_id' => 6,
                'test_id' => 162,
                'test_type' => 'test_case',
                'address_id' => 1,
                'appointment_date' => '2025-03-19',
                'appointment_time' => '16:30:00',
                'amount' => 130.0,
                'test_discount_amount' => 130.0,
                'collection_type' => 'home',
                'total_amount' => 141.9,
                'submission_status' => 'pending',
                'test_case_status' => NULL,
                'rejected_id' => 3,
                'by_suggestion' => 0,
                'cancellation_reason' => NULL,
                'symptoms' => 'Fever',
                'reschedule_reason' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-03-19 17:30:06',
                'updated_at' => '2025-03-19 17:32:28',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'status' => 'completed',
                'customer_id' => 3,
                'other_member_id' => NULL,
                'vendor_id' => 4,
                'lab_id' => 2,
                'test_id' => 186,
                'test_type' => 'test_case',
                'address_id' => 2,
                'appointment_date' => '2025-03-20',
                'appointment_time' => '11:40:00',
                'amount' => 300.0,
                'test_discount_amount' => 300.0,
                'collection_type' => 'home',
                'total_amount' => 331.0,
                'submission_status' => 'reject',
                'test_case_status' => NULL,
                'rejected_id' => NULL,
                'by_suggestion' => 0,
                'cancellation_reason' => NULL,
                'symptoms' => 'Fever',
                'reschedule_reason' => NULL,
                'created_by' => 3,
                'updated_by' => 1,
                'deleted_by' => 1,
                'created_at' => '2025-03-19 17:49:26',
                'updated_at' => '2025-03-19 17:56:20',
                'deleted_at' => '2025-03-19 17:56:20',
            ),
            10 => 
            array (
                'id' => 11,
                'status' => 'pending',
                'customer_id' => 3,
                'other_member_id' => NULL,
                'vendor_id' => 4,
                'lab_id' => 2,
                'test_id' => 186,
                'test_type' => 'test_case',
                'address_id' => 2,
                'appointment_date' => '2025-03-20',
                'appointment_time' => '11:40:00',
                'amount' => 300.0,
                'test_discount_amount' => 300.0,
                'collection_type' => 'home',
                'total_amount' => 331.0,
                'submission_status' => 'pending',
                'test_case_status' => NULL,
                'rejected_id' => 10,
                'by_suggestion' => 0,
                'cancellation_reason' => NULL,
                'symptoms' => 'Fever',
                'reschedule_reason' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-03-19 17:56:20',
                'updated_at' => '2025-03-19 17:56:20',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}